# Generated by Django 3.0.7 on 2020-06-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.CharField(max_length=100)),
                ('twitter_link', models.CharField(max_length=100)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.Business')),
            ],
        ),
    ]
