# Generated by Django 3.0.7 on 2020-06-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200630_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialnetworklinkstwitter',
            old_name='facebook_link',
            new_name='twitter_link',
        ),
    ]
