# Generated by Django 3.0.7 on 2020-07-01 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20200630_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworklinkstwitter',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Business'),
        ),
    ]
