# Generated by Django 3.0.7 on 2020-07-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200701_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworklinksfacebook',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Business'),
        ),
    ]
